### ISSUE TITLE
Unable to open assets\shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by gnany07** [codezoned/PyFry#13]
gmale@GMALE-M-R0DA:~/Documents/GitHub/PyFry$ python PyFry.py 
objc[35976]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff989f33d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12395af50). One of the two will be used. Which one is undefined.
picture location =  ['/Users/gmale/Documents/GitHub/PyFry/test.jpg']
Traceback (most recent call last):
  File "PyFry.py", line 124, in <module>
    main()
  File "PyFry.py", line 114, in main
    img = addFlare(img)
  File "PyFry.py", line 54, in addFlare
    **predict = dlib.shape_predictor("assets\shape_predictor_68_face_landmarks.dat")
RuntimeError: Unable to open assets\shape_predictor_68_face_landmarks.dat**

I don't know if this is macos specific issue or not.
While I tried to run PyFry.py, dlib is not able to open "shape_predictor_68_face_landmarks.dat" which is under assets folder.

**Comment by gnany07** [comment]
The issue is resolved by adding absolute path of dat file.
I know this is cosmetic issue but anyone who clones the repo and tries to run PyFry.py faces the problem.
I will raise the PR with the fix.
